INSERT INTO categoria (id, nome, slug, ordem, imagem)
VALUES
    (1, 'Body Splash', 'body-splash', 1, 'body-splash.jpg'),
    (2, 'Bolsas e Mochilas', 'bolsas-e-mochilas', 2, 'bolsas-e-mochilas.jpg'),
    (3, 'Cuidado para o Cabelo', 'cuidado-cabelo', 3, 'cuidado-cabelo.jpg'),
    (4, 'Cuidados para Pele', 'cuidados-pele', 4, 'cuidados-pele.jpg'),
    (5, 'Gloss Labial', 'gloss-labial', 5, 'gloss-labial.jpg'),
    (6, 'Kit para Presentear', 'kit-presentear', 6, 'kit-presentear.jpg'),
    (7, 'Maquiagem', 'maquiagem', 7, 'maquiagem.jpg'),
    (8, 'Variados', 'variados', 8, 'variados.jpg');

INSERT INTO produto (id, nome, descricao, preco, imagem, categoria_id)
VALUES
    (1, 'Spray finalizador cachos', 'Spray finalizador que define os cachos, reduz o frizz e proporciona brilho e maciez aos fios.', 24.99, '1.jpg', 3),
    (2, 'Spray térmico Rhenuks', 'Protetor térmico que ajuda a proteger os cabelos do calor do secador, chapinha e modeladores.', 24.99, '2.jpg', 3),
    (3, 'Spray finalizador Truss', 'Finalizador profissional que controla o frizz, oferece proteção térmica e deixa os fios sedosos.', 109.99, '3.jpg', 3),
    (4, 'Sabonete líquido corporal', 'Sabonete líquido corporal com espuma cremosa que limpa delicadamente e deixa a pele perfumada.', 19.99, '4.jpg', 4),
    (5, 'Esfoliante corporal Fenza', 'Esfoliante corporal que remove células mortas, promovendo uma pele mais lisa, macia e renovada.', 24.99, '5.jpg', 4),
    (6, 'Hidratante facial fenza barbie', 'Hidratante facial inspirado na linha Barbie, ideal para manter a pele hidratada e suave.', 19.99, '6.jpg', 4),
    (7, 'Hidratante corporal', 'Hidratante corporal de rápida absorção que ajuda a nutrir e proteger a pele diariamente.', 24.99, '7.jpg', 4),
    (8, 'Primer Ruby kisses', 'Primer que minimiza a aparência dos poros, controla a oleosidade e prolonga a maquiagem.', 44.99, '8.jpg', 7),
    (9, 'Primer vizzela', 'Primer facial com efeito suavizante que prepara a pele para uma maquiagem duradoura.', 54.99, '9.jpg', 7),
    (10, 'Primer Max love', 'Primer leve que uniformiza a pele, reduz o brilho excessivo e melhora a fixação da maquiagem.', 14.99, '10.jpg', 7),
    (11, 'Blindagem Dapop', 'Blindagem para maquiagem que aumenta a durabilidade dos produtos e ajuda na resistência à umidade.', 19.99, '11.jpg', 7),
    (12, 'Bolsa', 'Bolsa versátil e elegante, ideal para complementar o visual em diversas ocasiões.', 69.99, '12.jpg', 2),
    (13, 'Rímel trópico Ruby Rose', 'Máscara para cílios que proporciona volume, definição e efeito marcante ao olhar.', 24.99, '13.jpg', 7),
    (14, 'Rímel Melu', 'Máscara para cílios que alonga, define e realça o olhar com acabamento uniforme.', 24.99, '14.jpg', 7),
    (15, 'Rímel Melu Rosa', 'Máscara para cílios com embalagem rosa que oferece alongamento e volume aos fios.', 24.99, '15.jpg', 7),
    (16, 'Paleta de sombra', 'Paleta de sombras com cores versáteis para criar maquiagens discretas ou sofisticadas.', 24.99, '16.jpg', 7),
    (17, 'Bolsa lateral', 'Bolsa lateral prática e moderna, perfeita para o dia a dia e passeios.', 59.99, '17.jpg', 2),
    (18, 'Bolsa', 'Bolsa compacta com design elegante, ideal para transportar itens essenciais.', 59.99, '18.jpg', 2),
    (19, 'Pó Banana', 'Pó Banana com acabamento aveludado que auxilia na selagem da maquiagem e iluminação da pele.', 15.00, '19.jpg', 7),
    (20, 'Rímel ruby Rose tropico', 'Máscara para cílios da linha Trópico que proporciona volume intenso e longa duração.', 24.99, '20.jpg', 7),
    (21, 'Rímel melu Laranja', 'Máscara para cílios Melu com embalagem laranja que alonga e define os fios.', 24.99, '21.jpg', 7),
    (22, 'Rímel melu Rosa', 'Máscara para cílios Melu com embalagem rosa que oferece volume e destaque ao olhar.', 24.99, '22.jpg', 7),
    (23, 'Serum facial', 'Sérum facial com textura leve que auxilia na hidratação e revitalização da pele.', 24.99, '23.jpg', 4),
    (24, 'Base facial Bruna tavares', 'Base facial de alta cobertura com acabamento natural e longa duração.',84.99, '24.jpg', 4),
    (25, 'Gloss chocolate', 'Gloss labial com aroma de chocolate que proporciona brilho e hidratação aos lábios.', 15.00, '25.jpg', 5),
    (26, 'Bolsas', 'Bolsa espaçosa e estilosa, ideal para acompanhar a rotina com praticidade.', 79.99, '26.jpg', 2),
    (27, 'Body Splesh', 'Body Splash com fragrância suave e refrescante para perfumar a pele ao longo do dia.', 39.99, '27.jpg', 1),
    (28, 'Body Splesh', 'Body Splash com perfume delicado e sensação refrescante, ideal para uso diário.', 39.99, '28.jpg', 1),
    (29, 'Body Splesh', 'Body Splash de fragrância agradável que deixa a pele perfumada e renovada.', 39.99, '29.jpg', 1),
    (30, 'Body Splesh', 'Body Splash com aroma marcante e excelente fixação para prolongar a sensação de frescor.', 56.99, '30.jpg', 1),
    (31, 'Kit olumpils', 'Kit para presentear contendo produtos selecionados para cuidados e beleza em uma embalagem especial.', 69.99, '31.jpg', 6),
    (32, 'Gloss labial', 'Gloss labial com acabamento brilhante que hidrata e valoriza os lábios.', 19.99, '32.jpg', 5);

INSERT INTO caracteristica (nome)
VALUES
    ('Vegano'),
    ('Cruelty Free'),
    ('Hidratante'),
    ('Longa Duração'),
    ('Efeito Matte'),
    ('Brilho Intenso'),
    ('Proteção Térmica'),
    ('Compacto'),
    ('Premium'),
    ('Alta Pigmentação'),
    ('Perfumado'),
    ('Sem Parabenos'),
    ('Aço Inox'),
    ('Resistente à Água'),
    ('Uso Diário');

INSERT INTO produto_caracteristica (produto_id, caracteristica_id)
VALUES
    (1, 11),
    (1, 4),
    (2, 3),
    (2, 6),
    (3, 3),
    (3, 9),
    (4, 9),
    (4, 15),
    (5, 7),
    (5, 6),
    (6, 3),
    (6, 15),
    (7, 3),
    (7, 12),
    (8, 3),
    (8, 2),
    (9, 10),
    (9, 5),
    (10, 13),
    (10, 8),
    (11, 8),
    (11, 15),
    (12, 5),
    (12, 10),
    (13, 9),
    (13, 10),
    (14, 11),
    (14, 3),
    (15, 3),
    (15, 6);

INSERT INTO usuario (usuario, senha)
VALUES
    ('admin', '$2y$10$XrJ8oSYnxpwyb2w6l5ReBumPE8TYiVGjZLNaoy06hzzS7lZGUGJF6');